targets:
  dev:
    default: true
    workspace:
      host: ${env.DATABRICKS_HOST}
    run_as:
      service_principal_name: Databricks-SP
    variables:
      catalog: dev_catalog
      schema: dev_schema
