targets:
  dev:
    default: true
    workspace:
      host: ${env.DATABRICKS_HOST}
    run_as:
      user_name: ajitp@bitwiseglobal.net
    variables:
      catalog: dev_catalog
      schema: dev_schema
