targets:
  dev:
    default: true   # mark dev as default target
    variables:
      catalog: hive_metastore   # or 'main' if you have Unity Catalog
      schema: demo_dev
    overrides:
      resources.jobs.etl_demo_job.name: dbx-bundle-poc-dev-etl
