targets:
  dev:
    default: true
    workspace:
      host: ${env.DATABRICKS_HOST}
    run_as:
      user_name: rohitazure9@gmail.com
    variables:
      catalog: dev_catalog
      schema: dev_schema
