name: Deploy Databricks Bundle

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Choose environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install CLI
      - name: Install Databricks CLI
        run: |
          curl -L https://github.com/databricks/cli/releases/download/v0.264.2/databricks_cli_0.264.2_linux_amd64.tar.gz -o /tmp/databricks.tar.gz
          tar -xzf /tmp/databricks.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/databricks
          databricks version

      # Select secrets based on target
      - name: Set environment variables
        run: |
          TARGET="${{ github.event.inputs.target }}"
          echo "TARGET=$TARGET" >> $GITHUB_ENV

          if [ "$TARGET" = "dev" ]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }}" >> $GITHUB_ENV
          elif [ "$TARGET" = "qa" ]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_QA }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_QA }}" >> $GITHUB_ENV
          elif [ "$TARGET" = "prod" ]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_PROD }}" >> $GITHUB_ENV
            echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PROD }}" >> $GITHUB_ENV
          else
            echo "❌ Unknown target: $TARGET"
            exit 1
          fi

      - name: Sanity check
        run: |
          if [ -z "$DATABRICKS_HOST" ] || [ -z "$DATABRICKS_TOKEN" ]; then
            echo "❌ Missing Databricks secrets for $TARGET"
            exit 1
          fi
          echo "✅ Using Databricks host: $DATABRICKS_HOST"

      # Example: Bundle deploy
      - name: Deploy bundle
        run: |
          databricks bundle validate
          databricks bundle deploy
